version: '3.6'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    hostname: homeassistant
    volumes:
      - ${PWD}/homeassistant:/config
    ports:
      - "8123:8123"
    environment:
      TZ: "America/Sao_Paulo"